# Generated by Django 5.2.1 on 2025-06-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="circuit_info",
            field=models.TextField(default="정보없음"),
        ),
    ]
