# Generated by Django 5.2.1 on 2025-06-19 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guide",
            name="image",
            field=models.ImageField(blank=True, upload_to="guides/"),
        ),
        migrations.AddField(
            model_name="guide",
            name="summary",
            field=models.TextField(default="소개 내용이 없습니다", max_length=500),
            preserve_default=False,
        ),
    ]
