# Generated by Django 5.2.1 on 2025-06-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_guide_created_at_guide_image_guide_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guide",
            name="image",
        ),
        migrations.AlterField(
            model_name="guide",
            name="summary",
            field=models.TextField(max_length=600),
        ),
    ]
